### ISSUE TITLE
The root & SAP administrator passwords should be optional

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/saphanabootstrap-formula#2]
We're using this Salt formula in the Terraform deployments where we use SSH public keys.  These passwords should be optional IMHO.

```
        root_user: 'root'
        root_password: 'linux'
        system_user_password: 'Qwerty1234'
        sapadm_password: 'Qwerty1234'
```

**Comment by arbulu89** [comment]
@ricardobranco777 
As discussed, these passwords are required by SAP software to install everything correctly, so we cannot remove them.

**Comment by ricardobranco777** [comment]
I would:

- Remove these default passwords so it fails unless the user explicitly sets them.  It happens a lot while deploying in public cloud to see bots trying to brute-force their way in to the servers trying every password for root. But there's also the problem with default passwords for databases.
- Add a hardening step before installation to prevent SSH password logins and only allow SSH public keys.

**Comment by arbulu89** [comment]
@ricardobranco777

About the 1st point, as far as I know, this parameters are mandatory if you want to install HANA from a config file. You need to fill this configuration file with this parameters. Otherwise, the installation is not available, hblcm fails.

About the 2nd, I don't really think that this formula should take care of SSH stuff, I guess this will depend on the user system configuration,
This formulas only installs HANA.

**Comment by ricardobranco777** [comment]
I would let the installation fail if the passwords are not set, so the user sets them.

**Comment by arbulu89** [comment]
Finally we have agreed that this changes must be done in other project as this is only an example file, and is not provided with the installed package.
